### ISSUE TITLE
tests fails because of FFmpeg 

### ISSUE THREAD

**Issue by naarkhoo** [scikit-video/scikit-video#102]
Hi there

I am using FFmpeg 4.0.2, with python 3.6 - however can't make the scikit-video installed as I wish ...
`nosetests -v skvideo/ `

Pillow==4.1.1
scikit-learn==0.18.1
scikit-video==1.1.10
scipy==0.19.0
sklearn==0.0
wrapt==1.10.11

```
(VisionPy36) bash-3.2$ nosetests -v skvideo/
skvideo.tests.test_IOfail.test_failedread ... ok
skvideo.tests.test_IOfail.test_failedwrite ... ok
skvideo.tests.test_IOfail.test_failedextension ... ok
skvideo.tests.test_ffmpeg.test_FFmpegReader ... ERROR
skvideo.tests.test_ffmpeg.test_FFmpegReader_16bits ... ERROR
skvideo.tests.test_ffmpeg.test_FFmpegReader_fps ... ERROR
skvideo.tests.test_ffmpeg.test_FFmpegWriter ... ERROR
skvideo.tests.test_libav.test_LibAVReader_16bits ... SKIP: LibAV required for this test.
skvideo.tests.test_libav.test_LibAVReader_aboveversion9 ... SKIP: LibAV required for this test.
skvideo.tests.test_libav.test_LibAVWriter_Gray2RGBHack_Gray ... SKIP: LibAV required for this test.
skvideo.tests.test_libav.test_LibAVWriter_Gray2RGBHack_gray16be ... SKIP: LibAV required for this test.
skvideo.tests.test_libav.test_LibAVWriter_Gray2RGBHack_gray16le ... SKIP: LibAV required for this test.
skvideo.tests.test_libav.test_LibAVWriter_Gray2RGBHack_ya8 ... SKIP: LibAV required for this test.
skvideo.tests.test_libav.test_LibAVWriter_aboveversion9 ... SKIP: LibAV required for this test.
skvideo.tests.test_measure.test_measure_MSSSIM ... ERROR
skvideo.tests.test_measure.test_measure_BRISQUE ... ERROR
skvideo.tests.test_measure.test_measure_Viideo ... ERROR
skvideo.tests.test_measure.test_measure_VideoBliinds ... ERROR
skvideo.tests.test_measure.test_measure_STRRED ... SKIP: Disabled pending BLAS check
skvideo.tests.test_measure.test_measure_SSIM ... ERROR
skvideo.tests.test_measure.test_measure_NIQE ... ERROR
skvideo.tests.test_measure.test_measure_MAE ... ERROR
skvideo.tests.test_measure.test_measure_MSE ... ERROR
skvideo.tests.test_measure.test_measure_PSNR ... ERROR
skvideo.tests.test_motion.test_ES ... ok
skvideo.tests.test_motion.test_4SS ... ok
skvideo.tests.test_motion.test_3SS ... ok
skvideo.tests.test_motion.test_N3SS ... ok
skvideo.tests.test_motion.test_SE3SS ... ok
skvideo.tests.test_motion.test_ARPS ... ok
skvideo.tests.test_motion.test_DS ... ok
skvideo.tests.test_path.test_FFmpeg_paths ... FAIL
skvideo.tests.test_path.test_LibAV_paths ... SKIP: LibAV required for this test.
skvideo.tests.test_pattern.test_sinusoid_ffmpeg ... ERROR
skvideo.tests.test_pattern.test_noisepattern_ffmpeg ... ERROR
skvideo.tests.test_pattern.test_noisepattern_libav ... SKIP: LibAV required for this test.
skvideo.tests.test_pattern.test_sinusoid_libav ... SKIP: LibAV required for this test.
skvideo.tests.test_scenedet.test_scenedet ... ERROR
skvideo.tests.test_vread.test_vread2x ... ERROR
skvideo.tests.test_vread.test_vread ... ERROR
skvideo.tests.test_vread.test_vread_raw1_ffmpeg ... ERROR
skvideo.tests.test_vread.test_vread_raw2_ffmpeg ... ERROR
skvideo.tests.test_vread.test_vread_raw2_libav_aboveversion9 ... ok
skvideo.tests.test_vreader.test_vreader_ffmpeg ... ERROR
skvideo.tests.test_vreader.test_vreader_libav_version12 ... SKIP: LibAV required for this test.
skvideo.tests.test_vwrite.test_vreader_ffmpeg ... ERROR
skvideo.tests.test_vwrite.test_vreader_libav ... ok

======================================================================
ERROR: skvideo.tests.test_ffmpeg.test_FFmpegReader
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_ffmpeg.py", line 18, in test_FFmpegReader
    reader = skvideo.io.FFmpegReader(skvideo.datasets.bigbuckbunny(), verbosity=0)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_ffmpeg.test_FFmpegReader_16bits
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_ffmpeg.py", line 44, in test_FFmpegReader_16bits
    reader16 = skvideo.io.FFmpegReader(skvideo.datasets.bigbuckbunny(), outputdict={'-pix_fmt':'rgb48le'}, verbosity=0)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_ffmpeg.test_FFmpegReader_fps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_ffmpeg.py", line 79, in test_FFmpegReader_fps
    reader = skvideo.io.FFmpegReader(skvideo.datasets.bigbuckbunny(), outputdict={"-r": "10"}, verbosity=0)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_ffmpeg.test_FFmpegWriter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_ffmpeg.py", line 113, in test_FFmpegWriter
    writer.writeFrame(outputdata[i])
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 468, in writeFrame
    self._warmStart(M, N, C, im.dtype)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 439, in _warmStart
    self._createProcess(self.inputdict, self.outputdict, self.verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 108, in _createProcess
    stdout=self.DEVNULL, stderr=sp.STDOUT)
  File "/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/anaconda3/envs/VisionPy36/bin/ffmpeg'

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_MSSSIM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 49, in test_measure_MSSSIM
    ref = skvideo.io.vread(vidpaths[0], as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_BRISQUE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 62, in test_measure_BRISQUE
    dis = skvideo.io.vread(vidpaths, as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_Viideo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 83, in test_measure_Viideo
    dis = skvideo.io.vread(vidpaths, as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_VideoBliinds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 90, in test_measure_VideoBliinds
    dis = skvideo.io.vread(vidpaths, as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_SSIM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 115, in test_measure_SSIM
    ref = skvideo.io.vread(vidpaths[0], as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_NIQE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 144, in test_measure_NIQE
    ref = skvideo.io.vread(vidpaths, as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_MAE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 157, in test_measure_MAE
    ref = skvideo.io.vread(vidpaths[0], as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_MSE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 168, in test_measure_MSE
    ref = skvideo.io.vread(vidpaths[0], as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_measure.test_measure_PSNR
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_measure.py", line 179, in test_measure_PSNR
    ref = skvideo.io.vread(vidpaths[0], as_grey=True)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_pattern.test_sinusoid_ffmpeg
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_pattern.py", line 79, in test_sinusoid_ffmpeg
    pattern_sinusoid('ffmpeg')
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_pattern.py", line 20, in pattern_sinusoid
    skvideo.io.vwrite("sinusoid1d.yuv", sinusoid1d)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 64, in vwrite
    writer.writeFrame(videodata[t])
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 468, in writeFrame
    self._warmStart(M, N, C, im.dtype)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 439, in _warmStart
    self._createProcess(self.inputdict, self.outputdict, self.verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 108, in _createProcess
    stdout=self.DEVNULL, stderr=sp.STDOUT)
  File "/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/anaconda3/envs/VisionPy36/bin/ffmpeg'

======================================================================
ERROR: skvideo.tests.test_pattern.test_noisepattern_ffmpeg
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_pattern.py", line 89, in test_noisepattern_ffmpeg
    pattern_noise('ffmpeg')
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_pattern.py", line 52, in pattern_noise
    skvideo.io.vwrite("randomNoisePattern.yuv", randomNoiseData, backend=backend)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 64, in vwrite
    writer.writeFrame(videodata[t])
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 468, in writeFrame
    self._warmStart(M, N, C, im.dtype)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 439, in _warmStart
    self._createProcess(self.inputdict, self.outputdict, self.verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 108, in _createProcess
    stdout=self.DEVNULL, stderr=sp.STDOUT)
  File "/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/anaconda3/envs/VisionPy36/bin/ffmpeg'

======================================================================
ERROR: skvideo.tests.test_scenedet.test_scenedet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_scenedet.py", line 24, in test_scenedet
    vid = skvideo.io.vread(vidpath)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_vread.test_vread2x
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vread.py", line 14, in test_vread2x
    videodata = skvideo.io.vread(skvideo.datasets.bigbuckbunny())
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_vread.test_vread
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vread.py", line 18, in test_vread
    videodata = skvideo.io.vread(skvideo.datasets.bigbuckbunny())
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_vread.test_vread_raw1_ffmpeg
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vread.py", line 127, in test_vread_raw1_ffmpeg
    _rawhelper1("ffmpeg")
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vread.py", line 37, in _rawhelper1
    bunnyMP4VideoData1 = skvideo.io.vread(skvideo.datasets.bigbuckbunny(), num_frames=1, backend=backend)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_vread.test_vread_raw2_ffmpeg
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vread.py", line 141, in test_vread_raw2_ffmpeg
    _rawhelper2("ffmpeg")
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vread.py", line 93, in _rawhelper2
    bunnyMP4VideoData1 = skvideo.io.vread(skvideo.datasets.bigbuckbunny(), num_frames=1, outputdict=pipingDict.copy(), backend=backend)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_vreader.test_vreader_ffmpeg
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vreader.py", line 40, in test_vreader_ffmpeg
    _vreader("ffmpeg")
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vreader.py", line 21, in _vreader
    for frame in reader:
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 251, in vreader
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

======================================================================
ERROR: skvideo.tests.test_vwrite.test_vreader_ffmpeg
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vwrite.py", line 39, in test_vreader_ffmpeg
    _vwrite("ffmpeg")
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_vwrite.py", line 25, in _vwrite
    skvideo.io.vwrite(outputfile, outputdata, backend=backend)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/io.py", line 64, in vwrite
    writer.writeFrame(videodata[t])
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 468, in writeFrame
    self._warmStart(M, N, C, im.dtype)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/abstract.py", line 439, in _warmStart
    self._createProcess(self.inputdict, self.outputdict, self.verbosity)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/io/ffmpeg.py", line 108, in _createProcess
    stdout=self.DEVNULL, stderr=sp.STDOUT)
  File "/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/anaconda3/envs/VisionPy36/bin/ffmpeg'

======================================================================
FAIL: skvideo.tests.test_path.test_FFmpeg_paths
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/nohextaka/Documents/Projects/scikit-video/skvideo/tests/test_path.py", line 23, in test_FFmpeg_paths
    assert current_version != "0.0.0", "FFmpeg version not parsed."
AssertionError: FFmpeg version not parsed.

----------------------------------------------------------------------
Ran 47 tests in 0.577s

FAILED (SKIP=12, errors=22, failures=1)

```

**Comment by beyondmetis** [comment]
I don't think we ever tested with FFmpeg versions > 3. It looks like it can't find ffprobe, which is used for the video metadata. It could be that the newest ffprobe output isn't recognized. This should definitely be fixed, since scikit-video should work with the latest packages (at a bare minimum)

**Comment by Meixu-Chen** [comment]
The test suite has been modernized in v1.1.12: pixel-level comparisons that were sensitive to FFmpeg version have been replaced with tolerance-based checks (`rtol=0.01`). GitHub Actions CI now validates against Python 3.10–3.13 on both Linux and macOS with modern FFmpeg — all 8 matrix jobs pass.
