### ISSUE TITLE
outputdict data strucutre

### ISSUE THREAD

**Issue by victorCardeal** [scikit-video/scikit-video#150]
Hi I'v pass much time looking for examples on documentation how pattern outputdict parameter on function :=
   skvideo.io.FFmpegWriter()
in my code I call function like this in line 23:
`import skvideo.io
import skvideo.datasets
import numpy as np
import argparse
import cv2
import time

def threshOneFrame(frame):
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(frame, (7, 7), 0)
    """cv2.threshold(blurred,20,255, cv2.THRESH_BINARY)"""
    #thresh = cv2.adaptiveThreshold( blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 4)
    thresh = cv2.Canny(blurred,25,40).astype(np.uint8)
    #thresh = thresh.astype(np.uint8)
    return thresh

ap = argparse.ArgumentParser()
ap.add_argument("-v", "--video", required=True,
	help="path to input video file")
args = vars(ap.parse_args())
video = skvideo.io.FFmpegReader(args["video"])
lapstime = time.time()
videoWriter = skvideo.io.FFmpegWriter("outputvideo"+time.ctime(lapstime)+".mp4",outputdict={'width':'1080','height':'352','r_frame_rate':'30'})

for frame in video.nextFrame():
    videoWriter.writeFrame(threshOneFrame(frame))

videoWriter.close()`

that returns me an error 

Traceback (most recent call last):
  File "/home/vcardeal/.local/lib/python3.8/site-packages/skvideo/io/abstract.py", line 514, in writeFrame
    self._proc.stdin.write(vid.tostring())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vcardeal/.local/lib/python3.8/site-packages/skvideo/io/abstract.py", line 519, in writeFrame
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
/usr/bin/ffmpeg -y -f rawvideo -pix_fmt gray -s 352x640 -i - width 1080 height 352 r_frame_rate 30 /home/vcardeal/Documentos/processamento de imagens/pyImageResearch/file-video-stream/binarizeVideo/outputvideoWed Nov 11 19:05:43 2020.mp4

FFMPEG STDERR OUTPUT:

Process finished with exit code 1

**Comment by Meixu-Chen** [comment]
`outputdict` is a plain Python dict mapping FFmpeg flag strings to their values — e.g. `outputdict={'-vcodec': 'libx264', '-crf': '23'}`. Keys and values are both strings, passed verbatim to FFmpeg. The full flag reference is FFmpeg's documentation: https://ffmpeg.org/ffmpeg.html. Closing as a usage question.
