### ISSUE TITLE
measure/data is missing after installation from Git

### ISSUE THREAD

**Issue by stoyanovgeorge** [scikit-video/scikit-video#153]
I have installed the scikit-video from Github following your instructions and then I have tried to measure the NIQE of a video, but I got an error, that the `niqe_image_params.mat` is missing and when I have checked it appears that the whole `data/` dir is missing so I had to copy it manually from cloned directory to the `/usr/lib/<python_version>/site-packages/<scikit_video_version>/skvideo/measure/data` directory. I guess you have forgotten to copy this particular directory in the `setup.py`. 

By the way, if I install `scikit-video` with `pip` in `python-3.9` I am getting the `scipy.misc` error about `imresize`, so maybe it is a good idea to update the pip version with the fix.

**Comment by stg7** [comment]
this error is also affecting the example videos, (installation was done freshly from the git version to avoid the imresize) 
```
>>> import skvideo.datasets
>>> import skvideo.io
>>> videodata = skvideo.io.vread(skvideo.datasets.bigbuckbunny())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/PATH/venv/lib/python3.8/site-packages/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/PATH/venv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/PATH/venv/lib/python3.8/site-packages/skvideo/io/abstract.py", line 69, in __init__
    self.size = os.path.getsize(filename)
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/PATH/venv/lib/python3.8/site-packages/skvideo/datasets/data/bigbuckbunny.mp4'
>>> 
```
and the solution is already provided in pull request [#156](https://github.com/scikit-video/scikit-video/pull/156)

**Comment by Meixu-Chen** [comment]
Fixed in v1.1.12 (tag: [v1.1.12](https://github.com/scikit-video/scikit-video/releases/tag/v1.1.12)).

The `skvideo/measure/data/` directory (including `niqe_image_params.mat` and `frames_modelparameters.mat`) is now correctly included in the installed package. The old `setup.py` did not declare these data files properly; the new `pyproject.toml` build uses setuptools' automatic package data discovery, which picks them up correctly. You can verify after installation:

```python
import skvideo.measure
import skvideo.io, skvideo.datasets
# NIQE should now work without a manual data copy
scores = skvideo.measure.niqe(skvideo.io.vread(skvideo.datasets.bigbuckbunny(), as_grey=True)[:2])
```
