### ISSUE TITLE
ffmpeg write stalls occassionally

### ISSUE THREAD

**Issue by mattyb** [scikit-video/scikit-video#19]
Similar to #14, writing seems to stall randomly on OS X. I'm executing the same process (copying a few frames from a number of different AVI files and writing to a single mp4). It randomly stalls at different video files.

CTRL-C yields:
```
Traceback (most recent call last):
  File "./parse.py", line 36, in <module>
    writer.writeFrame(f)
  File "/usr/local/lib/python2.7/site-packages/skvideo/io/ffmpeg.py", line 439, in writeFrame
    self._proc.stdin.write(vid.tostring())
```

version info:
```
 ffmpeg -V
ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
```

```
$ python
Python 2.7.9 (default, Dec 15 2014, 10:01:34)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skvideo
>>> print(skvideo.__file__)
/usr/local/lib/python2.7/site-packages/skvideo/__init__.pyc
```

**Comment by beyondmetis** [comment]
Very annoying problem. I suspect that this is an issue with output pipes, which definitely needs to be addressed. My guess is that the standard output buffer fills up, blocking the ffmpeg subprocess from further work.

I'll see if I can reproduce the issue.

**Comment by beyondmetis** [comment]
Alright, I've applied a fix. Let me know if you still experience this issue.

**Comment by mattyb** [comment]
2cc1582 seems to have fixed it! Thanks for the quick response!
