### ISSUE TITLE
Windows executable path support

### ISSUE THREAD

**Issue by grovduck** [scikit-video/scikit-video#21]
Great package - it's very useful for my research.  Unfortunately, I'm using Windows and initially had problems with skvideo bonking when calling 'ffmpeg' and associated executables.  I did an ugly hack like this:
```
# get the correct exe name based on OS
ffprobe_exe = "ffprobe"
ffmpeg_exe = "ffmpeg"
avprobe_exe = "avprobe"
avconv_exe = "avconv"
mediainfo_exe = "mediainfo"
if os.name == "nt":
    ffprobe_exe += ".exe"
    ffmpeg_exe += ".exe"
    avprobe_exe += ".exe"
    avconv_exe += ".exe"
    mediainfo_exe += ".exe"
```
in `skvideo\__init__.py` and then change calls like this:

```
version = check_output([_FFMPEG_PATH + "/ffmpeg", "-version"])
```
to this:
```
version = check_output([_FFMPEG_PATH + "/" + ffmpeg_exe, "-version"])
```
It looks like there is a nice little cross-platform [where package](https://github.com/hweickert/where) that will correctly identify exe paths and may be useful in switching out the logic in the ```which``` function.  In fact, it looks like the only thing you're using ```_FFMPEG_PATH```, ```_AVCONV_PATH```, and ```_MEDIAINFO_PATH``` for are to concatenate to the exe name when issuing commands?  I think you could just use the output of the where command as the first argument to many of these calls, e.g.
```
import where
from skvideo.utils import check_output
ffmpeg_exe = where.where('ffmpeg')[0]
version = check_output([ffmpeg_exe, '-version'])
```
I'd be happy to write a PR, but thought you might have an idea of how you wanted to implement this.

**Comment by beyondmetis** [comment]
Thank you for taking the time to bring this to my attention!

I'd like to make this package more compatible with Windows. The only thing I'd change specifically is minimizing external package dependencies. The where package you linked looks like it uses the MIT license, which allows direct incorporation into scikit-video.

I'm not sure if you have time, but I noticed that you have experience with appveyor? Scikit-video would benefit from this, so that Windows gets tested prior to packaged releases.

**Comment by beyondmetis** [comment]
Windows should be supported now, based on the information you provided. Let me know if you have problems.

**Comment by grovduck** [comment]
@beyondmetis, sorry for just dropping this.  I just tested against 87089a9 and it works like a charm.  I also ran tests and had to make a couple of edits based on being on python 2.7.  These were one of two things:

* Testing accumulation in `test_ffmeg.py`, `test_libav.py`, and `test_vreader.py`, I made the denominator a float to ensure floating-point division (e.g. `float(T * M * N * C)`)
* In `test_measure.py`, I wasn't getting the decimal precision on a couple of tests, notably `test_measure_BRISQUE` and `test_measure_VideoBliinds`.  I had to set BRISQUE to 7 and VideoBliinds to 4.

Thanks for making this change.  My "experience" with appveyor is really just toying around with it, so I'm probably not the right person to pick that up.  But I'm happy to write up notes on what I needed to do to make it work with Windows if that's helpful.

**Comment by AndersonReyes** [comment]
@beyondmetis @grovduck  
I still get the error 

```
for frame in skvideo.io.vreader(v_path):
  File "C:\Users\Anderson\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\io\io.py", line 240,
in vreader
    assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.
```

but 

'''
C:\Users\Anderson>where ffmpeg
C:\Libs\ffmpeg-3.2.2-win64-static\bin\ffmpeg.exe
'''

**Comment by AndersonReyes** [comment]
@beyondmetis actually nvm I use the pip version and I doubt it has been updated to reflect github I'll install github version

**Comment by grovduck** [comment]
@AndersonReyes, yep that was the trick for me.

**Comment by beyondmetis** [comment]
@AndersonReyes That is correct. The pip version hasn't been updated in roughly a month. It'll be updated soon after the next round of bug fixes.

@grovduck  Thanks for testing! I'll see if I can figure out those precision issues. Since this is often due to an out-of-date numpy/scipy package, what version of numpy/scipy are you using?

**Comment by grovduck** [comment]
@beyondmetis, here is my setup.  I'm pulling wheels for numpy/scipy from the [Christoph Golhke site](http://www.lfd.uci.edu/~gohlke/pythonlibs/), maybe something with the addition of the Intel Math Kernel Library is affecting precision issues?

```
numpy==1.12.0+mkl
scipy==0.18.1
sk-video==1.1.7
```

**Comment by sanaullahmanzoor1988** [comment]
@grovduck  kindly help me..


File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\io\io.py", line 240, in vreader
    assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.

**Comment by AndersonReyes** [comment]
@grovduck you installed it using pip or fr

**Comment by AndersonReyes** [comment]
or from github?*

**Comment by sanaullahmanzoor1988** [comment]
using pip

**Comment by AndersonReyes** [comment]
@sanaullahmanzoor1988 use the github version scroll up he explains why.  Although I don't know if he haz updated pip version yet.

Note I tagged wrong person ealier lol

**Comment by sanaullahmanzoor1988** [comment]
Detailed error view)
C:\Users\bismil\Documents\Python Scripts\LipNet-master\evaluation>python predict.py models/weights04.h5 samples/id2_vcd_swwp2s.mpg
Using TensorFlow backend.

Loading data from disk...
Traceback (most recent call last):
File "predict.py", line 46, in 
video, result = predict(sys.argv[1], sys.argv[2])
File "predict.py", line 20, in predict
video.from_video(video_path)
File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 119, in from_video
frames = self.get_video_frames(path)
File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 172, in get_video_frames
frames = np.array([frame for frame in videogen])
File "c:\users\bismil\documents\python scripts\lipnet-master\lipnet\lipreading\videos.py", line 172, in 
frames = np.array([frame for frame in videogen])
File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\io\io.py", line 240, in vreader
assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.

**Comment by beyondmetis** [comment]
The pip version has not been updated yet. Try github version of scikit video and see if that fixes your problem.

**Comment by sanaullahmanzoor1988** [comment]
after installing scikit video 
from       https://github.com/scikit-video/scikit-video
I executed 
>>> import skvideo
>>> print(skvideo.__file__)
C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\__init__.py


means now scikit-video is working but still got

Error:

File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\skvideo\io\io.py", line 240, in vreader
    assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.

**Comment by sanaullahmanzoor1988** [comment]
New error:

videogen = skvideo.io.vreader(path)
AttributeError: module 'skvideo.io' has no attribute 'vreader'

**Comment by beyondmetis** [comment]
Make sure you import skvideo.io

**Comment by sanaullahmanzoor1988** [comment]
After removing sk-video in python 3.5 
my code working ...


because scikit-video is getting conflict with sk-video

for python 3 remove sk-video

@AndersonReyes  @beyondmetis @grovduck  thanks all <3 :)

**Comment by nitingulati7** [comment]
I am getting the similar error can you please suggest the alternative or work around.


  File "C:\ProgramData\Anaconda3\lib\site-packages\skvideo\io\io.py", line 133, in vread
    assert _HAS_FFMPEG, "Cannot find installation of real FFmpeg (which comes with ffprobe)."

**Comment by beyondmetis** [comment]
I do suggest the alternative. Install from github and also delete all mention of your current scikit-video install.

**Comment by nitingulati7** [comment]
I am new to python, Can you please share the steps on how to install the package from github. Thanks !!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndersonReyes** [comment]
@nitingulati7    https://github.com/scikit-video/scikit-video/blob/master/README.rst

Under installation and dependecies the github part its relative straight forward. Install dependencies using pip install

**Comment by nitingulati7** [comment]
@AndersonReyes I followed the steps but I still getting the same error, There some issue where _HAS_FFMPEG is setting to O or null
here is my code snippet
import skvideo.io


skvideo.setFFmpegPath("D:/ffmpeg/bin")
# a frame from the bigbuckbunny sequence
vid = skvideo.io.vread("D:/scikit-video-master/scikit-video-master/doc/examples/vid_luma_frame1.png")
T, M, N, C = vid.shape

print("Number of frames: %d" % (T,))
print("Number of rows: %d" % (M,))
print("Number of cols: %d" % (N,))
print("Number of channels: %d" % (C,))

**Comment by AndersonReyes** [comment]
@nitingulati7 what's in your bin folder?

**Comment by beyondmetis** [comment]
@nitingulati7 does it matter that you are using forward slashes on a windows computer? Also, have you tried running the setFFmpegPath function two times in a row, as in #38 ?

**Comment by nitingulati7** [comment]
@AndersonReyes : in the bin folder i have exe for ffmpeg, ffprobe & ffplay  which i had downloaded from ffmpeg.org

@beyondmetis: SetFFmpegpath command works fine after changing code in skvideo\__init__.py line no: 308
    if os.path.isfile(_FFMPEG_PATH + "/ffmpeg**.exe**") and os.path.isfile(_FFMPEG_PATH + "/ffprobe.**exe**"):
        _HAS_FFMPEG = 1

But it failed when I am trying to use the reader, some where in the code _HAS_FFMPEG get reset to false

I also tried to run "test_ffmpeg.py" but it doesn't find _HAS_FFMPEG as true and skips the function execution

**Comment by nitingulati7** [comment]
and I am using python 3.6

**Comment by tmatthias29** [comment]
Just a note, a way to solve/avoid the forward slashes on window would be to use `os.path.normpath()` and/or the rawstring character in front of the string.

**Comment by beyondmetis** [comment]
@nitingulati7 this may have been fixed just recently. Let me know if you are still having issues.

**Comment by nitingulati7** [comment]
@beyondmetis No it didn't work for me.

**Comment by beyondmetis** [comment]
@nitingulati7 I will need to inspect using python3.6 and possibly also a Windows 10 machine to understand what's missing.

**Comment by gregnordin** [comment]
Just a note that I ran into the same problem of sk-video not being able to find ffmpeg, but on Mac OS 10.12.4. I uninstalled sk-video and then followed the directions on the README page and installed sk-video from github and now it works.

**Comment by beyondmetis** [comment]
Thanks. It might be getting close to time for a new release.

**Comment by gregnordin** [comment]
Yeah, I would definitely say that if `pip install...` results in this error on Mac OS and Windows, it would be really good to update the code `pip install...` creates a working package. If I weren't so motivated to get it working, and didn't know to look in the issues, I would have given up and tried an alternative. This is not to be critical, just realistic. I really appreciate what you've done in creating this package.

**Comment by beyondmetis** [comment]
I don't have access to a mac right now, so I haven't been able to test pip on that platform. I have tested that pip install sk-video works great on Windows and several Linux flavors. I'm not sure why your system has this issue, but I'm glad you were able to get it working in the end.

**Comment by gregnordin** [comment]
I wish I could point to a concrete reason for the problem, but am glad that this issue was open to direct me toward doing a direct install from the github repository. I probably should have thought of that myself... :)

**Comment by carlodri** [comment]
installed with `pip install sk-video` on Windows 10x64 with python 3.6, no problems at all

**Comment by Thaumaturgy** [comment]
@carlodri I'm getting the same error:
assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.
I'm using Windows 10 and did what you suggested.
