### ISSUE TITLE
skvideo.io.ffprobe not working sometimes

### ISSUE THREAD

**Issue by usmanm** [scikit-video/scikit-video#45]
When I run `ffprobe` from the command line, it emits metadata, but `skvideo.io` isn't parsing it properly.

```
usmanm@usmanm-puget:~/identidata/facey/fixtures (master)*$ ffprobe videos/video0.mov 
ffprobe version 3.3-1~16.04.york1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version='1~16.04.york1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'videos/video0.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2017-06-14T18:28:36.000000Z
  Duration: 00:00:02.65, start: 0.000000, bitrate: 651 kb/s
    Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 480x360, 557 kb/s, 20 fps, 20 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2017-06-14T18:28:36.000000Z
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 78 kb/s (default)
    Metadata:
      creation_time   : 2017-06-14T18:28:36.000000Z
      handler_name    : Core Media Data Handler
usmanm@usmanm-puget:~/identidata/facey/fixtures (master)*$ ipython
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import skvideo.io

In [2]: skvideo.io.ffprobe('videos/video0.mpg')
Out[2]: {}
```

This causes `FFmpegReader` to throw the following error:
```
[ERROR] 2017-06-16 14:37:00,760 (383) tasks: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.
Traceback (most recent call last):
  File "/identidata/facey/tasks.py", line 137, in _extract_faces_from_video
    reader = skvideo.io.FFmpegReader(f.name)#, inputdict=inputdict)
  File "/usr/local/lib/python2.7/dist-packages/skvideo/io/ffmpeg.py", line 130, in __init__
    raise ValueError("No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.
```

**Comment by beyondmetis** [comment]
Can you send your video to tgoodall@utexas.edu? Then I can quickly debug this issue

**Comment by usmanm** [comment]
Sorry, it turns out the issue was with something else. I was writing a video buffer to a file and then calling `ffprobe` on it, but sometimes the file wasn't properly flushed to disk.
