### ISSUE TITLE
error reading high resolution videos

### ISSUE THREAD

**Issue by identidata** [scikit-video/scikit-video#48]
I am getting some runtime errors with high resolution videos. Code I am using is:

    videogen = skvideo.io.vread('video.avi')

And what I get is:

    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/io.py", line 148, in vread
    for idx, frame in enumerate(reader.nextFrame()):
    File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/ffmpeg.py", line 293, 
    in nextFrame yield self._readFrame()
    File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/ffmpeg.py", line 277, 
    in_readFrame
    s = self._read_frame_data()
    File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/ffmpeg.py", line 271, 
    in _read_frame_data
    raise RuntimeError("%s" % (err1,))
    RuntimeError

**Comment by beyondmetis** [comment]
I tested scikit-video with up to 4k resolution. What resolutions are you loading?

**Comment by identidata** [comment]
apologies for the delay, it is not that much: 

`(u'@height', u'1280'), (u'@coded_width', u'720')

but I still get the error thread above.`

**Comment by beyondmetis** [comment]
Alright, it's probably not related to resolution, but it is a problem I have never encountered with my videos. Care to link me to a problem file? My email is tgoodall@utexas.edu

**Comment by identidata** [comment]
hi Tom, yes of course - I have sent videos before (alejandro@identidata.io)
