### ISSUE TITLE
skvideo.io.vread throws an exception where skvideo.io.vreader does not

### ISSUE THREAD

**Issue by identidata** [scikit-video/scikit-video#50]
for the same video. 
Here is the exception.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/io.py", line 253, in vre
ader
    for frame in reader.nextFrame():
  File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/ffmpeg.py", line 293, in
 nextFrame
    yield self._readFrame()
  File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/ffmpeg.py", line 277, in
 _readFrame
    s = self._read_frame_data()
  File "/usr/local/lib/python2.7/dist-packages/sk_video-1.1.8-py2.7.egg/skvideo/io/ffmpeg.py", line 271, in
 _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError

```

**Comment by beyondmetis** [comment]
I'm assuming this is happening for one video in particular, since these functions have been well tested. I'll take a look using some videos you already sent me.

**Comment by identidata** [comment]
hi Todd,

No, this happens with some videos (see example). This is one of our
engineers, i.e. no privacy concerns :).

Two comments:

1) the exception is thrown either when you use skvideo.io.vread or when you
use skvideo.io.vreader and cast the vreader object into a list (which I
understand is the same as the former).

my understanding is that vreader is an iterator and reads the frames one by
one, whereas vread tries to read the entire video in one go. If there is a
problem with a particular frame, vread with through the exception, while
vreader may let you extract a few frames.

This may be the reason.

Best,

Alejandro



Alejandro Simkievich
CEO | *identidata.io <http://identidata.io>*
M: +55 (11) 99634-6673 <+55%2011%2099634-6673>
skype: asimkievich

**Comment by Meixu-Chen** [comment]
The traceback here is from Python 2.7 with an old version of scikit-video. scikit-video v1.1.12 requires Python 3.10+ and the test suite passes on Python 3.10–3.13. Please upgrade and reopen if you see this on a modern Python.
