### ISSUE TITLE
AttributeError: module 'skvideo.io' has no attribute 'vread'

### ISSUE THREAD

**Issue by sree94** [scikit-video/scikit-video#51]
I am using python 3.6 and have installed sk-video. I am not able to read the video using vread.

**Comment by sree94** [comment]
Hi any update on this issue?

**Comment by beyondmetis** [comment]
1. Have you installed FFmpeg? 
2. Have you imported skvideo.io?

**Comment by sree94** [comment]
Ya I have done both.

**Comment by beyondmetis** [comment]
What does the error output say?

**Comment by sree94** [comment]
This is the full Error message:

runfile('C:/Users/sreeram/Vread.py', wdir='C:/Users/sreeram')
Traceback (most recent call last):

  File "<ipython-input-4-10967f8ca88f>", line 1, in <module>
    runfile('C:/Users/sreeram/Vread.py', wdir='C:/Users/sreeram')

  File "C:\Users\sreeram\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\sreeram\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/sreeram/Vread.py", line 10, in <module>
    videodata = skvideo.io.vread(skvideo.datasets.bigbuckbunny())

AttributeError: module 'skvideo.io' has no attribute 'vread'

**Comment by sree94** [comment]
Hi any update on this?

**Comment by beyondmetis** [comment]
What is the output of:

import skvideo
print(skvideo.__file__)

Also share a short snippet of code, so I can test your problem.

**Comment by sree94** [comment]
Output 
AttributeError: module 'skvideo' has no attribute '__file__'

Code:

import skvideo.io
import skvideo.datasets
videodata = skvideo.io.vread(skvideo.datasets.bigbuckbunny())
print(videodata.shape)

**Comment by beyondmetis** [comment]
When you print(skvideo.\_\_file__), you should see something like this:
```
>>> import skvideo
>>> print(skvideo.__file__)
/usr/lib/python2.7/site-packages/sk_video-1.1.8-py2.7.egg/skvideo/__init__.pyc
>>> 
```

If you do not, python does not know where to find the skvideo package. Your code looks fine.

**Comment by sree94** [comment]
I have uninstalled scikit-video and installed sk-video.Still the error persists .How can this be solved?

**Comment by beyondmetis** [comment]
It seems that you are able to load some module, it just can't seem to do
anything with it. Are you able to check it's version from your python
script?

What if you open a python terminal separate from spyder and try to print
the file location from there?

**Comment by sree94** [comment]
I get the same error when I run it in a separate python script.

**Comment by beyondmetis** [comment]
Weird. You are the only one experiencing this issue that I know of. Are you using windows, Linux, or mac? Windo

**Comment by sree94** [comment]
I am using windows

**Comment by beyondmetis** [comment]
Are you using pip to install skvideo? Are other packages installed through pip working?

**Comment by sree94** [comment]
Ya I use pip to install all packages and it work's fine.

**Comment by NonvolatileMemory** [comment]
got the same problem fixed by pip install sk-video

**Comment by Swall0w** [comment]
I had the same problem.
```bash
pip install sk-video
```
It works for me. Thank you.

**Comment by zengxianyu** [comment]
I have the same problem, and 
```
pip install sk-video
```
dosen't work for me

**Comment by AkashNagaraj** [comment]
I have the same problem, and

pip install sk-video

dosen't work for me
