### ISSUE TITLE
Import error when using skvideo.io

### ISSUE THREAD

**Issue by hasanagh** [scikit-video/scikit-video#58]
I am trying to import skvideo.io in python 3.6.3 but getting an import error. I installed skvideo through pip and it was installed successfully.

The is the error I am getting
`
Traceback (most recent call last): File "", line 1, in import skvideo.io File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\skvideo__init__.py", line 3, in from .utils import check_output, where File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\skvideo\utils__init__.py", line 10, in from .edge import canny File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\skvideo\utils\edge.py", line 8, in import scipy.ndimage File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage__init__.py", line 161, in from .filters import * File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\ndimage\filters.py", line 37, in from scipy.misc import doccer File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\misc__init__.py", line 67, in from scipy.interpolate._pade import pade as _pade File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\interpolate__init__.py", line 175, in from .interpolate import * File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\interpolate\interpolate.py", line 20, in import scipy.linalg File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg__init__.py", line 186, in from .misc import * File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg\misc.py", line 5, in from .blas import get_blas_funcs File "C:\Users\Hasan\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\linalg\blas.py", line 196, in from scipy.linalg import _fblas ImportError: DLL load failed: The specified module could not be found.`

**Comment by beyondmetis** [comment]
Did you install scipy?
