### ISSUE TITLE
Issue with io/ffmpeg.py

### ISSUE THREAD

**Issue by praateekmahajan** [scikit-video/scikit-video#60]
RuntimeError: Traceback (most recent call last):
  File "/home/praateek/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "<ipython-input-10-a53d73bbb9a6>", line 32, in __getitem__
    vid = skvideo.io.vread(self.__xs[index])
  File "/usr/local/lib/python2.7/dist-packages/skvideo/io/io.py", line 148, in vread
    for idx, frame in enumerate(reader.nextFrame()):
  File "/usr/local/lib/python2.7/dist-packages/skvideo/io/ffmpeg.py", line 293, in nextFrame
    yield self._readFrame()
  File "/usr/local/lib/python2.7/dist-packages/skvideo/io/ffmpeg.py", line 277, in _readFrame
    s = self._read_frame_data()
  File "/usr/local/lib/python2.7/dist-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError

So I am loading around 10,000 videos, and this issue seems to pop randomly. First I thought maybe it's one corrupted video files, but after having tried on different machines, I am sure the error just pops from any arbitary file.

```
        vid = skvideo.io.vread(filename)
        frames, width, height, channels = vid.shape
        time_steps = int(frames/self.timestep) #sample rate is number of frames to extract per second 
        return vid[::self.timestep]
```

I'm sharing my code just in case it helps figure it out, but I believe the behavior is random, because it does it load a lot of videos before throwing that error.

**Comment by beyondmetis** [comment]
Thanks for sharing. I know there is a problem like this when roughly half your system memory is used by python prior to a ffmpeg call.

How large are your largest videos?

**Comment by praateekmahajan** [comment]
Longest video is 71 seconds in length. All the videos have a frame rate of 25fps and resolution 320x240. 

It is the UCF101 dataset if you want to look at it more. But yes, videos aren’t fancy neither corrupted

**Comment by beyondmetis** [comment]
Hmm, strange. If it's not a specific video, and you are loading them one-at-a-time, then you shouldn't have an issue like this. FFmpeg is pretty stable. From the error, it seems like the FFmpeg process starts but then has a chance of not behaving correctly. Memory issues usually fail early at the ffprobe stage, so it's likely something else. I'm not sure what.

**Comment by n17r4m** [comment]
I am running into what may or may not be the same issue as this, #48, and #50. Perhaps ffmpeg has subtlely changed it's output format in a recent release? (I'm using ffmpeg 3.4 fwiiw). 

I traced the problem to ffmpeg.py around line 270, namely,
```
arr = np.fromstring(self._proc.stdout.read(framesize), dtype=np.uint8)
assert len(arr) == framesize
```

len(arr) is 0, (on what I believe is the end of the video), and thus the assertion error is thrown, which is then rethrown as a RuntimeError.

**Comment by beyondmetis** [comment]
@n17r4m Thanks for catching what looks like a bug. I'll look into this.

**Comment by d-acharya** [comment]
I encountered this same error. In my case, most likely, the video was not closed properly while writing. So while reading, it gives error with last frame. For comparision VLC player also warns "file index is broken or missing so seeking will not work correctly". So, this is probably because video was not written to file properly.

I would rather catch exception and continue rather than avoid last frame in all videos as @n17r4m suggested.

**Comment by Lazare** [comment]
What we can do to mitigate this problem:

stop yielding as soon as we get an empty frame.
- benefit : no more RuntimeException in case we overestimate the number of frames
- drawback : getShape() won't always give you the right number of frames (it can overestimate it never underestimate)

I'll check if there's a better way to estimate the true number of frames than what's already done in the Readers, but I don't think so except by reading the video file entirely if the number of frames is not present in the metadata.
I think whoever that in case of resample ("-r" option) the estimation can be improved, and I'm working on it.

**Comment by ajinkyaT** [comment]
Any updates on error?

**Comment by Lazare** [comment]
I don't have time to work on this project at the moment. I should be able to do it in August.

**Comment by fbenda** [comment]
I got the same issue while reading video files:
```
videogen = skvideo.io.vreader(args.input_video, outputdict=outpudict)
    for i, frame in enumerate(videogen):
        ...
```
my videos are 3840x1080 pixel and around 2-3 minutes long with 25fps, but it dies always before the 25ft frame:

```
Traceback (most recent call last):
  File ".../cv35/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
    assert len(arr) == framesize
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../src/main.py", line 77, in <module>
    main(sys.argv[1:])
  File ".../src/main.py", line 65, in main
    for i, frame in enumerate(videogen):
  File ".../cv35/lib/python3.5/site-packages/skvideo/io/io.py", line 253, in vreader
    for frame in reader.nextFrame():
  File ".../cv35/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame
    yield self._readFrame()
  File ".../cv35/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame
    s = self._read_frame_data()
  File ".../cv35/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError
```

My outputdict looks like: 
```
outpudict = {"-map": "0",
                 "-vcodec": "copy",
                 "-f": "mpegts"}
```

**Comment by evanfitzking** [comment]
Hello,

Having this problem as well.
<code>
Invalid UE golomb code
   Last message repeated 106 times
[matroska,webm @ 0x23d9540] Read error at pos. 3935349 (0x3c0c75)
len(ffprobe_result) 1802
Traceback (most recent call last):
 File "/home/hamsolo/.virtualenvs/hamsolo/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
   assert len(arr) == framesize
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "processNewClips.py", line 269, in <module>
   main()
 File "processNewClips.py", line 235, in main
   for (frame_number, frame_data, frame_time) in classifyVideoFrames(clip[1], args.jump):
 File "processNewClips.py", line 54, in classifyVideoFrames
   for frame in itertools.islice(videoReader, 0, None, jump):
 File "/home/hamsolo/.virtualenvs/hamsolo/lib/python3.5/site-packages/skvideo/io/io.py", line 253, in vreader
   for frame in reader.nextFrame():
 File "/home/hamsolo/.virtualenvs/hamsolo/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame
   yield self._readFrame()
 File "/home/hamsolo/.virtualenvs/hamsolo/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame
   s = self._read_frame_data()
 File "/home/hamsolo/.virtualenvs/hamsolo/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data
   raise RuntimeError("%s" % (err1,))
RuntimeError
</code>

**Comment by beyondmetis** [comment]
Since this error keeps happening, send me videos. I’ll debug and attempt to patch scikit-video once I can regularly reproduce the problem.

**Comment by husnejahan** [comment]
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

**Comment by LittleLittleTree** [comment]
Use "ffmpeg" command, try "ffmpeg -i vid1.avi vid2.avi" and use vid2.avi to replace vid1.avi. For me, it can solve this problem. May be there are some formats of videos that ffmpeg doesn't support.

**Comment by beyondmetis** [comment]
@LittleLittleTree If that command works, that means that ffmpeg supports loading the original video without any extra flags. This should work perfectly in scikit video. If that is not the case, I would like more information (with an example video file) so I can reproduce.

**Comment by jrbtaylor** [comment]
I'm also getting the error in `skvideo.io.vread`

**Comment by bmmlover** [comment]
I solved this problem by specifying correct codec in inputdict in FFmpegReader (in my case 'hevc'):
in_params = {'-vcodec': 'hevc'}
reader = FFmpegReader(filename, inputdict=in_params)

You can see appropriate codec in skvideo.io.ffprobe(filename)['video']['@codec_tag_string'].

**Comment by tailin1009** [comment]
I Just need some help!
When I use `skvideo.io.FFmpegReader`  to read videos in a for loop.
My memory is growing. I just want to release the resource after reading the video information!!!

**Comment by beyondmetis** [comment]
@tailin1009 The videos should be released when the handle to them goes out of scope on the next iteration of your for loop. Can you share some minimal code snippet with your problem?

**Comment by HudsonHuang** [comment]
> Use "ffmpeg" command, try "ffmpeg -i vid1.avi vid2.avi" and use vid2.avi to replace vid1.avi. For me, it can solve this problem. May be there are some formats of videos that ffmpeg doesn't support.

It solved my question, the FFmpegReader class might doesn't support some format as ffmpeg do.

**Comment by NagabhushanSN95** [comment]
> Use "ffmpeg" command, try "ffmpeg -i vid1.avi vid2.avi" and use vid2.avi to replace vid1.avi. For me, it can solve this problem. May be there are some formats of videos that ffmpeg doesn't support.

I was facing the same problem @LittleLittleTree 's solution worked for me too. Thanks!

**Comment by NagabhushanSN95** [comment]
I think I found the problem. In my system, in that particular conda environment, there was a python package `ffmpeg` installed. This python package always overrides default ffmpeg installed. So, scikit-video uses this python package instead of the default ffmpeg on the system. The command `ffmpeg -i vid1.avi vid2.avi` uses default ffmpeg and hence it works.

I uninstalled the ffmpeg python package. Now everything works well.
So, I guess it is not a problem with scikit-video.

**Comment by ZDL-Git** [comment]
@NagabhushanSN95 scikit-video built-in ffmpeg

**Comment by NagabhushanSN95** [comment]
Even i thought so. But this is what I found.

**Comment by Kennard123661** [comment]
I faced a similar issue to this. I use the in_params suggestion by @bmmlover but I still have the error. I fixed it by adding a `reader.close()` function at the end where:

```
    in_params = {'-vcodec': 'h264'}
    reader = vio.FFmpegReader(video_path, inputdict=in_params)
```

can someone verify whether this hack to fix it actually works?

**Comment by martinriven** [comment]
still gets this error

**Comment by Meixu-Chen** [comment]
This thread has accumulated multiple unrelated reports over the years (Python 2, different FFmpeg versions, different symptoms). v1.1.13 ships several improvements that touch this class of error:

- FFmpegWriter now surfaces FFmpeg's actual stderr instead of silently producing empty output (#111)
- FFmpegReader no longer leaks a process when verbosity>0 (#174)
- pathlib.Path is accepted at every filename entry point (#148, #163)
- Python 3.10–3.13 is now the supported version range

If you still hit a RuntimeError from `_read_frame_data` on v1.1.13 with modern Python and FFmpeg, please open a fresh issue with:
- The full FFmpeg version (`ffmpeg -version` first line)
- A small reproducer video if possible (or the failing video's ffprobe output)
- The full traceback

Stale-closing this thread to keep the backlog navigable. Release: https://github.com/scikit-video/scikit-video/releases/tag/v1.1.13
