### ISSUE TITLE
cannot convert pix_fmt

### ISSUE THREAD

**Issue by BeyondHeaven** [scikit-video/scikit-video#66]
The script I wrote:
```
inputdict = {"-pix_fmt":"rgb24"}
reader = skvideo.io.FFmpegReader(input_file,inputdict)
print reader.pix_fmt
writer = skvideo.io.FFmpegWriter(output_file)
for frame in reader.nextFrame():
    do something
```
Error occured
```
Traceback (most recent call last):
  File "VideoIO_test.py", line 27, in <module>
    for frame in reader.nextFrame():
  File "/usr/lib/python2.7/site-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame
    yield self._readFrame()
  File "/usr/lib/python2.7/site-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame
    s = self._read_frame_data()
  File "/usr/lib/python2.7/site-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError
```
If I set inputdict to "{}", it works but the pix_fmt is YUV
Any ideas?
Thanks!

**Comment by BeyondHeaven** [comment]
In ffmpeg,_read_frame_data(),
`arr = np.fromstring(self._proc.stdout.read(framesize), dtype=np.uint8)`
if I set pix_fmt=rgb24(or bgr24,nv12.etc),len(arr)=0

**Comment by beyondmetis** [comment]
Which version of ffmpeg do you have, and does that error occur immediately on reading the first frame?
