### ISSUE TITLE
Getting Error with Motion Analysis Example Code

### ISSUE THREAD

**Issue by Optidox** [scikit-video/scikit-video#76]
I'm trying to use the example motion code from the scikit-video website on videos of Overwatch practice range gameplay, but I'm getting two different problems depending on what video I use. For two 7 second long 60 fps 1280x720 videos, I'm getting the following error:

> Traceback (most recent call last):
  File "C:\Users\matth\PycharmProjects\OWAimAnalyzer\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 271, in _read_frame_data
    assert len(arr) == framesize
AssertionError

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:/Users/matth/PycharmProjects/OWAimAnalyzer/importTest.py", line 62, in <module>
    videodata = skvideo.io.vread(filename)
  File "C:\Users\matth\PycharmProjects\OWAimAnalyzer\venv\lib\site-packages\skvideo\io\io.py", line 148, in vread
    for idx, frame in enumerate(reader.nextFrame()):
  File "C:\Users\matth\PycharmProjects\OWAimAnalyzer\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 297, in nextFrame
    yield self._readFrame()
  File "C:\Users\matth\PycharmProjects\OWAimAnalyzer\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 281, in _readFrame
    s = self._read_frame_data()
  File "C:\Users\matth\PycharmProjects\OWAimAnalyzer\venv\lib\site-packages\skvideo\io\ffmpeg.py", line 275, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError

For a 2150 frame video (roughly 30 seconds) with the same recording specs, I get past line 62 and instead get the following error:

>Traceback (most recent call last):
  File "C:/Users/matth/PycharmProjects/OWAimAnalyzer/importTest.py", line 74, in <module>
    motionData = skvideo.motion.blockMotion(videodata)
  File "C:\Users\matth\PycharmProjects\OWAimAnalyzer\venv\lib\site-packages\skvideo\motion\block.py", line 942, in blockMotion
    luminancedata = rgb2gray(videodata)
  File "C:\Users\matth\PycharmProjects\OWAimAnalyzer\venv\lib\site-packages\skvideo\utils\__init__.py", line 345, in rgb2gray
    videodata = videodata[:, :, :, 0]*0.2989 + videodata[:, :, :, 1]*0.5870 + videodata[:, :, :, 2]*0.1140 
MemoryError

Also, further down, I was having an error pop up with xrange, so I changed it to range and now it doesn't have an error, but I'm unsure if my code will work with that change. I'd appreciate any insight you have into these issues, and thank you for the awesome image/video analysis libraries.

**Comment by beyondmetis** [comment]
Are you loading one video after another in the same python script?

**Comment by fbenda** [comment]
#60 looks similar than your first error. I have the same issue with my videos

**Comment by hamidreza-mahini** [comment]
I have the same issue with "Detecting Scene Boundaries example" and "bike.mp4" video. Unfortunately, #60 could not help me to solve this issue.

**Comment by hamidreza-mahini** [comment]
I solved this issue by installing python 3.7.3 64 bit instead of python 3.7.3 32 bit.

**Comment by Meixu-Chen** [comment]
It looks like this was resolved by switching to a 64-bit Python installation (as noted in the comments). The motion estimation module has also been updated in recent commits to fix NumPy 2.x compatibility. Closing as resolved.
