### ISSUE TITLE
Ability to read/write streams?

### ISSUE THREAD

**Issue by tokotchd** [scikit-video/scikit-video#81]
Is there any capability provided by scikit-video to read/write from streams rather than files?  I saw an ability for io.vreader() to read from webcams, can this be extended?

I.E. to replicate the behavior of directly calling ffmpeg, I would call:
ffmpeg -f dshow -i video="Virtual-Camera" -preset ultrafast -vcodec libx264 -tune zerolatency -b 900k -f mpegts udp://10.1.0.102:1234

Specifically what is being done here is writing to udp://10.1.0.102:1234

I've tried opening a ffmpegwriter to TCP/IP ports but it throws the error:
>>> skvideo.io.FFmpegWriter('127.0.0.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tokotchd/.local/lib/python3.5/site-packages/skvideo/io/ffmpeg.py", line 336, in __init__
    assert str.encode(self.extension).lower() in _FFMPEG_SUPPORTED_ENCODERS, "Unknown encoder extension: " + self.extension.lower()
AssertionError: Unknown encoder extension: .1

Which implies that it's trying to parse the dots in the IP as a file extension.

**Comment by beyondmetis** [comment]
This would be awesome. I haven't tested with streaming, and the webcam support was based on using a device file descriptor. Of course, if you can use FFmpeg for streaming, we can support it with skvideo. If you want to implement support for this, I'd be happy to accept the pull request. It's pretty easy to modify the FFMpegReader to check for IP addresses, but it looks like some additional setup is needed for playing with streams.

**Comment by tokotchd** [comment]
@beyondmetis I believe I've found the solution, though I am unsure (and unable to test) how it affects the library in its other modes...
in file ffmpeg, we assert that the extension makes sense if the video is not raw or in webcam mode.
 if israw != 0 or iswebcam != 0:
            inputdict['-pix_fmt'] = self.pix_fmt
        else:
            # check that the extension makes sense
            assert str.encode(self.extension).lower() in _FFMPEG_SUPPORTED_DECODERS, "Unknown decoder extension: " + self.extension.lower()

An exception needs to be made to this check in order to prevent a network address from being parsed like a file format. I.E. parsing "127.0.0.1:9001" as a ".1:9001" video format (which obviously doesn't exist).

My hack involves just checking the filename for the "://" and setting the webcam flag to true and seems to work well for me.  I can imagine, however a use case where this breaks another element of the library that I am not testing.

**Comment by tokotchd** [comment]
Created Pull Request:
https://github.com/scikit-video/scikit-video/pull/82

**Comment by Meixu-Chen** [comment]
Added in 1.1.14. `vread`/`vreader`/`vwrite` now accept HTTP(S) URLs and in-memory `BytesIO` objects in addition to local paths, so you can read and write without touching disk. Streaming-protocol output targets (e.g. `rtmp://`) are also supported on the write side: the writer now skips the file-only extension and directory checks for URL destinations and lets ffmpeg handle the network. See the non-local I/O examples in the 1.1.14 docs.
