### ISSUE TITLE
global_motion - ValueError: too many values to unpack

### ISSUE THREAD

**Issue by amarioncosmo** [scikit-video/scikit-video#94]
This code:
```
def global_motion(frame1, frame2):
    print(frame1.shape)
    print(frame2.shape)
    return skvideo.motion.globalEdgeMotion(frame1, frame2)
```
gives:
```
(216, 384)
(216, 384)
Traceback (most recent call last):
[...]
File "test_filters.py", line 366, in global_motion
    v = skvideo.motion.globalEdgeMotion(frame1, frame2)
  File "/usr/local/lib/python3.5/dist-packages/scikit_video-1.1.10-py3.5.egg/skvideo/motion/gme.py", line 73, in globalEdgeMotion
    E_1 = canny(frame1)
  File "/usr/local/lib/python3.5/dist-packages/scikit_video-1.1.10-py3.5.egg/skvideo/utils/edge.py", line 31, in canny
    M, N = frame.shape
ValueError: too many values to unpack (expected 2)
```

I'm using the last git version of skvideo. In this version these 2 lines have been added in gme.py line 63:
```
frame1 = vshape(frame1)
frame2 = vshape(frame2)
```
So now frame1 and frame2 have the shape (T, M, N, C) but the canny function has not been modified and the scipy.ndimage.correlate1d function take 2 dimensional array.

I fixed this issue by adding `frame = frame[0,:,:,0]` at the beginning of the canny function.

**Comment by beyondmetis** [comment]
Thanks for catching this!
